#decoupage d'une chaine de caractere (slicing)
college ='college bois de boulogne'
print(college[0])
print(college[8])
print(college[20])
print(college[-1])
print(college[-2])
print(college[8:12:1])
print(college[-8:-1])
print(college[0:20:3])
print(len(college))
print(college[:])
print(college[::])
print(college[::-1])